### ISSUE TITLE
Hosting on Azure

### ISSUE THREAD

**Issue by jonsamwell** [Accedia/appleauth-net#1]
Hi! Thanks for this library it is really useful.

Just a quick suggestion you might want to add to your readme.

For this code to work in an Azure web app the setting `WEBSITE_LOAD_USER_PROFILE  = 1` needs to be added to the web app settings in the Azure portal to allow the code to access the key store when it imports the private key needed to create the Apple secret (see https://stackoverflow.com/a/49649930/1162133).  Otherwise the code will fail here (https://github.com/Accedia/appleauth-net/blob/master/Cryptography/TokenGenerator.cs#L34) with a file not found exception.

Thanks!

**Comment by DanailStoichkov** [comment]
Hello!
Really glad that you found our library useful. Also, thanks very much for the feedback. This is a good catch since I also struggled with that when initially testing the flow. I will update the README.md accordingly and I will also try to provide a more precise explanation of what the exact cause for this issue is.

**Comment by jonsamwell** [comment]
Great thanks again @DanailStoichkov
