### ISSUE TITLE
An Error Occurred While Sending The Request.

### ISSUE THREAD

**Issue by ahmadfadlalla** [Accedia/appleauth-net#18]
Hey, I'm trying to get the authorization token, using the code below: 
`AuthorizationToken authorizationToken = await provider.GetAuthorizationToken(response.code, privateKey); `
However, I'm getting the following error: "An error occurred while sending the request.". Kindly find below the redirect Uri API I'm using:

```
[HttpPost]
public async Task HandleResponseFromApple(InitialTokenResponse response)
{
    string privateKey = System.IO.File.ReadAllText("path/to/file.p8");

    AppleAuthProvider provider = new AppleAuthProvider("MyClientID", "MyTeamID", "MyKeyID", "MyRedirectUrl", "SomeState");

    AuthorizationToken authorizationToken = await provider.GetAuthorizationToken(response.code, privateKey);
}
```

**Comment by DanailStoichkov** [comment]
@ahmadfadlalla I would need more information in order to help you out. 
First of all you can make sure you have followed strictly the guidelines for setting up ClientID, TeamID, Key, etc. 
If it's also possible can you get the network request from a tool like Fiddler or Postman and send a screenshot of the response that you get from Apple.

**Comment by ahmadfadlalla** [comment]
Thanks for your reply, I have managed to resolve this issue, it appears that the issue was due to the connection between the two servers, so I had to add the following line of code:` ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;` and it resolved the problem.
