### ISSUE TITLE
Potential NullReferenceException in SetUserInformation

### ISSUE THREAD

**Issue by DianaLaa** [Accedia/appleauth-net#6]
Glad to find this so that I can try out an alternative implementation to my own. I've been getting the dreaded `invalid_client` response from Apple. With your library, I'm getting a NullReferenceException. I'm not sure what is going on (Apple Sign-In used to work for us and no code changes were applied) but I wanted to report back that there is a potential NullRef exception in the method SetUserInformation. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AppleAuth.AppleAuthProvider.SetUserInformation(AuthorizationToken tokenResponse)
   at AppleAuth.AppleAuthProvider.<GetAuthorizationToken>d__23.MoveNext()
```

Looking at your source, either `deserializeUserInformation` is null, or `deserializeUserInformation.Claims is null` or `auth_time` is null.

**Comment by DanailStoichkov** [comment]
Hello,
Thank you for the feedback and sorry for the late response!
I will have to investigate this issue and see if it's possible to be because of something in the library. If you want you can attach an example request that you make to Apple, so I can try spot right away what causes the invalid_client error. In the meantime I will also fix the NullReferenceException.
